algoritmo "SomaParametrosReferencia"
var
   X, Y: Inteiro
Procedimento Soma (var A, B: Inteiro)
Inicio
      A <- A + 1
      B <- B + 2
      Escreval("O valor de A: ", A)
      Escreval("O valor de B: ", B)
      Escreval("A soma A + B: ", A + B)
FimProcedimento
inicio
      X <- 4
      Y <- 8
      Soma (X, Y)
      Escreval("Valor de X: ", X)
      Escreval("Valor de Y: ", Y)
fimalgoritmo